### ISSUE TITLE
[BUG] Credit abuse in [PRACTICE]

### ISSUE THREAD

**Issue by Linguistie** [SaengerItsWar/shavit-credits#8]
Got reported by a player that credits can be abused by finishing a map in practice mode (infinitely teleporting to a cp near a finishline and spamming it)

I haven't tried it myself yet, but I assume it's true

**Comment by SaengerItsWar** [comment]
ok this is funny cause normaly practice mode dosent let u make any time but the style segmented but for this style there is a check for this in the timer and also for the tas module
this is the code for this wich is in the plugin twice 
```sourcrpawn
char sStyleSpecialString[sizeof(stylestrings_t::sSpecialString)];
	Shavit_GetStyleStrings(style, sSpecialString, sStyleSpecialString, sizeof(sStyleSpecialString));
	
	if (StrContains(sStyleSpecialString, "segments") != -1)
		return;
	
	if (!g_cvTasEnabled.BoolValue)
		if (StrContains(sStyleSpecialString, "tas") != -1)
			return;
```

**Comment by Linguistie** [comment]
Well, I m using shavit 2.6.0 and this is what I just got
![image](https://user-images.githubusercontent.com/22871155/104899297-582f1300-5983-11eb-9c9c-b8d2cc2d2f9d.png)
"[Timer] WARNING: You're now in practice mode. Your times WILL NOT be saved and will be only displayed to you!"

those don't go into the database, but they do post a time in chat
I'll try to test it again and see what might have caused the players to receive the credits

EDIT2: interesting, one of the players told me that he was able to do it on fur_fix but can't do it on stref_cairo, maybe it's somehow  connected with switching tracks? He also said he was getting 5 credits and after switching to main and then back to bfur he started getting 10 

I'll let you know if I figure it out

**Comment by Linguistie** [comment]
those don't go into the database, but they do post a time in chat

**Comment by Linguistie** [comment]
![image](https://user-images.githubusercontent.com/22871155/104900793-2dde5500-5985-11eb-9483-4fc51bfc9cca.png)
pic from a guy

**Comment by SaengerItsWar** [comment]
ok i fixed what you meant and thank you for the report :)
https://github.com/SaengerItsWar/shavit-credits/raw/R1ko-Shop-Core-Fork/plugins/shavit-credits.smx

**Comment by Linguistie** [comment]
The issue is still there. All I needed to do is drop the new .smx file into plugins and nothing else, right? Well, looks like that didn't help, if I installed it correctly. Here are some screenshots.
![image](https://user-images.githubusercontent.com/22871155/105282530-3f0ea800-5bb7-11eb-85c6-ebe7b0d672f6.png)

**Comment by SaengerItsWar** [comment]
Did you restart the Server or changed the map? and did you downloaded the right version? cause your output says Zephyrus-Store Version?

**Comment by Linguistie** [comment]
I have changed tha map, yeah, these are several days old and the credits have been abused. No, I have not restarted the server, only sm plugins unloaded the old one, deleted from /plugins and put a new .smx in and sm plugins loaded it. I am using zephyrus-store version due to my shop being zephyrus, I got the .smx from directly downloading it

**Comment by Linguistie** [comment]
I'll attempt downloading it again later today and see what happens

**Comment by SaengerItsWar** [comment]
could you give me your full styles.cfg and say me which style you are using of it so that can i reproduce this.

**Comment by SaengerItsWar** [comment]
sry it's been a while i finaly found what you mean and i fixed it now in this version
